// <auto-generated />
namespace RentalAgency.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class moviemodelmodified : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(moviemodelmodified));
        
        string IMigrationMetadata.Id
        {
            get { return "201710192218101_movie-model-modified"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
